# Generated by Django 5.2.5 on 2025-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('villager', 'Villager'), ('admin', 'Admin')], default='villager', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('village_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
