# Generated by Django 5.2.5 on 2025-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mandi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mandi',
        ),
        migrations.AlterField(
            model_name='village',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='village',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='socioeconomic_status',
            field=models.CharField(max_length=50),
        ),
    ]
