# Generated by Django 5.2.5 on 2025-08-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_mandi_alter_village_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandi_name', models.CharField(max_length=255)),
                ('mandi_type', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
