# Generated by Django 5.2.5 on 2025-08-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mandi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('Monsoon', 'Monsoon'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], max_length=20)),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=100)),
                ('quantity_kg', models.BigIntegerField()),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.village')),
            ],
        ),
    ]
