# Generated by Django 5.2.5 on 2025-08-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='socioeconomic_status',
        ),
        migrations.AddField(
            model_name='village',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
