# Generated by Django 5.2.5 on 2025-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_village_socioeconomic_status_village_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandi',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mandi',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
