# Generated by Django 5.2.5 on 2025-08-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandi',
            name='state',
        ),
    ]
