# Generated by Django 5.2.5 on 2025-08-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_mandi_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='state',
        ),
    ]
