# Generated by Django 5.2.5 on 2025-08-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_village_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='state_name',
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='accounts.state'),
        ),
    ]
