# Generated by Django 5.2.5 on 2025-08-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_district_state_name_district_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandi',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandis', to='accounts.district'),
        ),
        migrations.AlterField(
            model_name='mandi',
            name='mandi_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mandi',
            name='mandi_type',
            field=models.CharField(choices=[('grain', 'Grain'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='accounts.district'),
        ),
    ]
