# Generated by Django 5.2.5 on 2025-09-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_roadvertex_fruits_grains_vegetables_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruits',
        ),
        migrations.DeleteModel(
            name='Grains',
        ),
        migrations.RemoveField(
            model_name='product',
            name='village',
        ),
        migrations.DeleteModel(
            name='Vegetables',
        ),
        migrations.AlterModelTable(
            name='road',
            table='roads_punjab',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
