# Generated by Django 5.2.5 on 2025-10-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_month', models.CharField(max_length=20)),
                ('submission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Submission',
                'verbose_name_plural': 'Product Submissions',
                'db_table': 'product_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
