# Generated by Django 5.2.5 on 2025-10-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_productsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSubmission',
        ),
    ]
